name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: print hello message
        run: echo "Hello GitAction"
      - name: print goodbye message
        run: |
          echo "Well Done!"
          echo "Good Bye Github Actions"
  
